// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmgEae6RZCdT-rGrOxbPOUORkNo3KfCQ',
    appId: '1:795709300858:web:de6c326e9552052f1d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    authDomain: 'iris-a0951.firebaseapp.com',
    storageBucket: 'iris-a0951.firebasestorage.app',
    measurementId: 'G-MGPN7JLBHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76ZxFLnA4Id_79-xj5UYWwpowM6pTQFA',
    appId: '1:795709300858:android:44271110b89c65311d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuH4Ih9NWDUT40p3r9UjWk4pZyEVnpuU',
    appId: '1:795709300858:ios:0be8084c6d7ffda11d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
    iosClientId: '795709300858-qlej57rrkq7f4gnr1jljikiel9hfhkk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.irisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuH4Ih9NWDUT40p3r9UjWk4pZyEVnpuU',
    appId: '1:795709300858:ios:0be8084c6d7ffda11d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
    iosClientId: '795709300858-qlej57rrkq7f4gnr1jljikiel9hfhkk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.irisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmgEae6RZCdT-rGrOxbPOUORkNo3KfCQ',
    appId: '1:795709300858:web:9d8f9f5994ca25a31d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    authDomain: 'iris-a0951.firebaseapp.com',
    storageBucket: 'iris-a0951.firebasestorage.app',
    measurementId: 'G-DKF52BZC73',
  );
}
