// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmgEae6RZCdT-rGrOxbPOUORkNo3KfCQ',
    appId: '1:795709300858:web:789781cd10821b6b1d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    authDomain: 'iris-a0951.firebaseapp.com',
    storageBucket: 'iris-a0951.firebasestorage.app',
    measurementId: 'G-Z9DWGYRLM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76ZxFLnA4Id_79-xj5UYWwpowM6pTQFA',
    appId: '1:795709300858:android:542552885e28b1601d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuH4Ih9NWDUT40p3r9UjWk4pZyEVnpuU',
    appId: '1:795709300858:ios:bc8f7c0a5a35d42d1d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
    androidClientId: '795709300858-130qo71uus354e6kpagk0k2qshe53gnl.apps.googleusercontent.com',
    iosClientId: '795709300858-ka59ogdofk378qs8icnnpc4j48aeh96j.apps.googleusercontent.com',
    iosBundleId: 'com.recovery.recoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuH4Ih9NWDUT40p3r9UjWk4pZyEVnpuU',
    appId: '1:795709300858:ios:bc8f7c0a5a35d42d1d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    storageBucket: 'iris-a0951.firebasestorage.app',
    androidClientId: '795709300858-130qo71uus354e6kpagk0k2qshe53gnl.apps.googleusercontent.com',
    iosClientId: '795709300858-ka59ogdofk378qs8icnnpc4j48aeh96j.apps.googleusercontent.com',
    iosBundleId: 'com.recovery.recoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmgEae6RZCdT-rGrOxbPOUORkNo3KfCQ',
    appId: '1:795709300858:web:584f5d435ff01bce1d1bc3',
    messagingSenderId: '795709300858',
    projectId: 'iris-a0951',
    authDomain: 'iris-a0951.firebaseapp.com',
    storageBucket: 'iris-a0951.firebasestorage.app',
    measurementId: 'G-G9Y2ZQ8K6Z',
  );
}
