name: iris_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  flutter:
    sdk: flutter

  # Varsayılan Ikonlar
  cupertino_icons: ^1.0.8

  # Firebase Paketleri
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0

  # UI ve Ekstra Ikonlar
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Resimler icin varlik klasoru tanimlamasi
  # Proje klasorunde 'assets' ve icinde 'images' klasoru olusturmayi unutma.
  assets:
    - assets/images/